[package]
name = "Personal_finance_1"
version = "0.1.0"
edition = "2024"

[dependencies]
clearscreen = "4.0.1"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0.140"
simply_colored = "0.1.0"
